export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      first_name: "Alice",
      last_name: "Johnson",
      phone: "+1 (646) 123-1234",
      email: "aj@test.test",
      address: "503 Broadway",
      city: "New York",
      twoFactoreIsSet: true,
      biometricsIsSet: false,
      notificationsActive: true,
      modules_completed: 5,
      security_score: 87,
    },
    {
      id: 2,
      first_name: "Bob",
      last_name: "Smith",
      phone: "+1 (212) 555-2345",
      email: "bob.smith@test.test",
      address: "123 Elm Street",
      city: "Los Angeles",
      twoFactoreIsSet: false,
      biometricsIsSet: true,
      notificationsActive: false,
      modules_completed: 3,
      security_score: 72,
    },
    {
      id: 3,
      first_name: "Carol",
      last_name: "Williams",
      phone: "+1 (415) 987-6543",
      email: "carol.williams@test.test",
      address: "456 Oak Avenue",
      city: "San Francisco",
      twoFactoreIsSet: true,
      biometricsIsSet: true,
      notificationsActive: true,
      modules_completed: 7,
      security_score: 95,
    },
    {
      id: 4,
      first_name: "David",
      last_name: "Brown",
      phone: "+1 (312) 444-5678",
      email: "david.brown@test.test",
      address: "789 Maple Drive",
      city: "Chicago",
      twoFactoreIsSet: false,
      biometricsIsSet: false,
      notificationsActive: false,
      modules_completed: 1,
      security_score: 64,
    },
    {
      id: 5,
      first_name: "Eve",
      last_name: "Davis",
      phone: "+1 (305) 321-9876",
      email: "eve.davis@test.test",
      address: "101 Pine Lane",
      city: "Miami",
      twoFactoreIsSet: true,
      biometricsIsSet: false,
      notificationsActive: true,
      modules_completed: 6,
      security_score: 78,
    },
    {
      id: 6,
      first_name: "Frank",
      last_name: "Miller",
      phone: "+1 (206) 555-3456",
      email: "frank.miller@test.test",
      address: "202 Cedar Road",
      city: "Seattle",
      twoFactoreIsSet: false,
      biometricsIsSet: true,
      notificationsActive: false,
      modules_completed: 8,
      security_score: 82,
    },
    {
      id: 7,
      first_name: "Grace",
      last_name: "Wilson",
      phone: "+1 (617) 777-8901",
      email: "grace.wilson@test.test",
      address: "303 Birch Street",
      city: "Boston",
      twoFactoreIsSet: true,
      biometricsIsSet: true,
      notificationsActive: true,
      modules_completed: 9,
      security_score: 91,
    },
    {
      id: 8,
      first_name: "Henry",
      last_name: "Moore",
      phone: "+1 (214) 333-4567",
      email: "henry.moore@test.test",
      address: "404 Spruce Court",
      city: "Dallas",
      twoFactoreIsSet: false,
      biometricsIsSet: false,
      notificationsActive: false,
      modules_completed: 4,
      security_score: 88,
    },
    {
      id: 9,
      first_name: "Ivy",
      last_name: "Taylor",
      phone: "+1 (602) 999-1234",
      email: "ivy.taylor@test.test",
      address: "505 Palm Boulevard",
      city: "Phoenix",
      twoFactoreIsSet: true,
      biometricsIsSet: false,
      notificationsActive: true,
      modules_completed: 2,
      security_score: 54,
    },
    {
      id: 10,
      first_name: "Jack",
      last_name: "Anderson",
      phone: "+1 (303) 444-7890",
      email: "jack.anderson@test.test",
      address: "606 Redwood Circle",
      city: "Denver",
      twoFactoreIsSet: false,
      biometricsIsSet: true,
      notificationsActive: false,
      modules_completed: 10,
      security_score: 69,
    },
    {
      id: 11,
      first_name: "Karen",
      last_name: "Thomas",
      phone: "+1 (702) 555-6789",
      email: "karen.thomas@test.test",
      address: "707 Fir Lane",
      city: "Las Vegas",
      twoFactoreIsSet: true,
      biometricsIsSet: true,
      notificationsActive: true,
      modules_completed: 0,
      security_score: 77,
    },
  ]);
}
